### ISSUE TITLE
Making the VSCode ext available from the Marketplace

### ISSUE THREAD

**Issue by melMass** [superfunc/usda-syntax#2]
Hi SF,

Do you have plans to upload the USD Highlighter on the VSCode MarketPlace ?
If not do you mind me doing so ? specifying the right credits of course.

Let me know.

Thanks

**Comment by superfunc** [comment]
Hi, thanks for your interest. I haven't had time to write the VSCode highlighter so this will have to wait until I've implemented it. So far I've only implemented sublime vim and emacs. I'll update this when I do.

**Comment by superfunc** [comment]
Gonna close this one out, someone else wrote a VSCode plugin for usda files https://github.com/AnimalLogic/AL_usd_vscode_extension, so now I don't have to :)
